version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    tty: true
    volumes:
      - ./nginx/config:/etc/nginx
      - ./nginx/logs:/var/log/nginx
      - ./nginx/html:/usr/share/nginx/html
    ports:
      - 80:80
